### PR TITLE
chore(crate2nix): change version in Cargo.toml

### PR DESCRIPTION
**Pull request by steveeJ**
this makes it easier which version of crate2nix is installed in any target environment. the intention of this change is to have the resulting commit tagged as `0.11.0-rc.3`.

see https://github.com/kolloch/crate2nix/issues/264

cc @Ericson2314

### CODE REVIEW

**Comment by Ericson2314** [comment]
oh oops thanks for that. I'll put on the right branch and tag a new one.

**Comment by steveeJ** [comment]
@Ericson2314 i think there's a regeneration step missing. currently testing locally and will push to this branch once i'm confident about it.

**Comment by Ericson2314** [comment]
Oh I just pushed to `release/0.11`. I guess we will be making RC 4! haha

**Comment by steveeJ** [comment]
@Ericson2314 yes. i'm confused now about the version on master still stating 0.10.0 in the manifest. should i base this PR on the `release/0.11` to make the version adjustment for `0.11.0-rc.4`?

**Comment by steveeJ** [comment]
> @Ericson2314 yes. i'm confused now about the version on master still stating 0.10.0 in the manifest. should i base this PR on the `release/0.11` to make the version adjustment for `0.11.0-rc.4`?

i did the above. i think it's fine as it's pushed here and can be merged and tagged :-)

also, thanks for your response :pray: :raised_hands:

**Pull request merged**
